-- Create srv_survei table
CREATE TABLE public.srv_survei (
    id integer NOT NULL,
    nama character varying(255) NOT NULL,
    periode_id integer,
    CONSTRAINT srv_survei_pkey PRIMARY KEY (id),
    CONSTRAINT fk_periode FOREIGN KEY (periode_id)
        REFERENCES public.srv_periode(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- Insert data from CSV
INSERT INTO public.srv_survei (id, nama) VALUES
(1, 'Enumeration Area (EA)/Pasar'),
(2, 'Survei Angkatan Kerja Nasional (SAKERNAS)'),
(3, 'Survei Penduduk Antar Sensus (SUPAS)'),
(4, 'Survei Sosial Ekonomi Nasional (SUSENAS)'),
(5, 'Survei Ekonomi Rumah Tangga Triwulanan (SERUTI)'),
(6, 'Pemutakhiran Data Perkembangan Desa'),
(7, 'Survei Perilaku Anti Korupsi (SPAK)'),
(8, 'Survei Pengukuran Tingkat Kebahagiaan (SPTK)'),
(9, 'Survei Komuter'),
(10, 'Kerangka Sampel Area (KSA)'),
(11, 'Survei Pertanian Tanaman Pangan/Ubinan'),
(12, 'Survei Perusahaan Hortikultura'),
(13, 'Survei Komoditas Strategis Perkebunan'),
(14, 'Updating Direktori Perusahaan Pertanian (DPP) dan Direktori Usaha Pertanian Lainnya (DUTL)'),
(15, 'Survei Perusahaan Perkebunan'),
(16, 'Laporan Tahunan Perusahaan Peternakan'),
(17, 'Laporan Pemotongan Ternak'),
(18, 'Laporan Tahunan Perusahaan Penangkapan Ikan'),
(19, 'Laporan Triwulanan Pelabuhan Perikanan dan Tempat Pelelangan Ikan'),
(20, 'Laporan Tahunan Perusahaan Budidaya Ikan'),
(21, 'Survei Perusahaan Kehutanan'),
(22, 'Survei Industri Besar dan Sedang (IBS)'),
(23, 'Survei Komoditas Perusahaan Industri Manufaktur'),
(24, 'Pemutakhiran Direktori Perusahaan Awal (DPA)'),
(25, 'Survei Tahunan Perusahaan Industri Manufaktur'),
(26, 'Survei IMK'),
(27, 'Survei Perusahaan Listrik'),
(28, 'Survei Perusahaan Panas Bumi'),
(29, 'Survei Perusahaan Pertambangan Non Migas'),
(30, 'Survei Perusahaan Penggalian Bahan Industri dan Konstruksi'),
(31, 'Survei Tahunan Usaha Penggalian Bahan Industri dan Konstruksi'),
(32, 'Captive Power'),
(33, 'Updating Direktori Perusahaan Pertambangan dan Energi'),
(34, 'Survei Perusahaan Air Bersih'),
(35, 'Survei Perusahaan Konstruksi'),
(36, 'Updating Direktori Perusahaan Konstruksi'),
(37, 'Survei Karakteristik Usaha Integrasi'),
(38, 'Survei Ekonomi (EWS)'),
(39, 'Updating Direktori Usaha/Perusahaan Ekonomi Lanjutan'),
(40, 'Post Enumeration Survey SE2026'),
(41, 'Pemutakhiran Kerangka Geospasial dan Muatan Wilkerstat'),
(42, 'Pendataan Ekspor dan Impor di Luar Dokumen Bea Cukai'),
(43, 'Survei Perdagangan Barang Domestik'),
(44, 'Survei Pola Distribusi Barang'),
(45, 'Survei Pola Usaha Non Pertanian'),
(46, 'Survei Jasa Penunjang Angkutan'),
(47, 'Survei Harga Produsen Sektor Industri Pengolahan, Pertambangan, dan Penggalian (HP)'),
(48, 'Survei Harga Produsen Sektor Jasa (HPJ)'),
(49, 'Survei Harga Produsen Beras di Penggilingan (HPBG)'),
(50, 'Survei Harga Perdagangan Besar'),
(51, 'Survei Harga Mesin dan Peralatan'),
(52, 'Survei Harga Produsen Sektor Pertanian (HPT)'),
(53, 'Survei Harga Properti Perumahan'),
(54, 'HK'),
(55, 'Survei Volume Penjualan Komoditas Spesifik'),
(56, 'Survei Pedagang Beras'),
(57, 'Survei Harga Produsen Identifikasi Komoditas Utama'),
(58, 'Survei Harga Kemahalan Konstruksi'),
(59, 'Survei Harga Produsen Perdesaan (HD)'),
(60, 'Survei Harga Konsumen Perdesaan (HKD)'),
(61, 'Survei Kesejahteraan Petani'),
(62, 'Survei Lembaga Keuangan Koperasi Simpan Pinjam'),
(63, 'Survei Statistik Keuangan BUMD'),
(64, 'Survei Lembaga Keuangan Pedagang Valuta Asing'),
(65, 'Survei Statistik Keuangan Keuangan Pemerintah Desa - K3'),
(66, 'Survei E-Commerce'),
(67, 'Survei Perusahaan/Usaha Penyedia Makan Minum (UMB)'),
(68, 'Survei Usaha/Perusahaan Daya Tarik Wisata'),
(69, 'Survei Usaha/Perusahaan Penyedia Jasa Akomodasi'),
(70, 'Updating Direktori Usaha Pariwisata'),
(71, 'Passenger Exit Survey (PES)'),
(72, 'Survei Wisatawan Nusantara'),
(73, 'Survei Khusus Triwulanan Neraca Barang'),
(74, 'Survei Khusus Triwulanan Neraca Jasa'),
(75, 'Indepth Study SEEA'),
(76, 'Survei Khusus Neraca Produksi (SKNP)'),
(77, 'Updating Direktori LNPRT'),
(78, 'Survei Khusus Lembaga Non Profit Triwulanan (SKLNPT)'),
(79, 'Survei Khusus Perusahaan Swasta Non-Finansial (SKPS)'),
(80, 'Survei Khusus Studi Penyusunan Perubahan Inventori (SKSPPI)'),
(81, 'Survei Penyusunan Disagregasi PMTB'),
(82, 'Survei Harga Barang dan Jasa (SHBJ)'),
(83, 'Survei Standar Biaya (SSB)');
